apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: travel-agency
type: Opaque
stringData:
  MONGODB_PASSWORD_USER: "user-db-password"
  MONGODB_PASSWORD_PACKAGE: "package-db-password"
  MONGODB_PASSWORD_ORDER: "order-db-password"
  MONGODB_PASSWORD_CUSTOMER: "customer-db-password"
  MONGODB_PASSWORD_MESSAGE: "message-db-password"
  MONGODB_PASSWORD_ADMIN: "admin-db-password"
  RABBITMQ_ERLANG_COOKIE: "change-me-erlang-cookie-secure"
