apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: travel-agency
data:
  NODE_ENV: "production"
  PORT: "3000"
  SERVICE_NAME: "gateway"
  RABBITMQ_URL: "amqp://admin:$(RABBITMQ_PASSWORD)@rabbitmq.travel-agency.svc.cluster.local:5672"
  USER_SERVICE_URL: "http://user-service:3001"
  PACKAGE_SERVICE_URL: "http://package-service:3002"
  ORDER_SERVICE_URL: "http://order-service:3003"
  CUSTOMER_SERVICE_URL: "http://customer-service:3004"
  MESSAGE_SERVICE_URL: "http://message-service:3005"
  EMAIL_SERVICE_URL: "http://email-service:3006"
  ADMIN_SERVICE_URL: "http://admin-service:3007"
