apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: travel-agency
data:
  rabbitmq.conf: |
    loopback_users.guest = false
    management.tcp.port = 15672
    management.listener.port = 15672
    management.listener.ssl = false
