apiVersion: v1
kind: Service
metadata:
  name: package-service-mongodb
  namespace: travel-agency
spec:
  selector:
    app: package-service-mongodb
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
