apiVersion: v1
kind: Service
metadata:
  name: package-service
  namespace: travel-agency
  labels:
    app: package-service
spec:
  selector:
    app: package-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
